### ISSUE TITLE
Once Read GitHub Docs about readme.md

### ISSUE THREAD

**Issue by Tirupatibalaji-Dev** [TheKaushikGoswami/SPIKE-Discord-Bot#2]

**Comment by TheKaushikGoswami** [comment]
Can You Explain What U wanna tell me?

**Comment by Tirupatibalaji-Dev** [comment]
once read docs

**Comment by TheKaushikGoswami** [comment]
I have already read, i didn't get what you wanna explain here?

**Comment by Tirupatibalaji-Dev** [comment]
bro if you can do then explain the process of installing and using. The
noob developer don't know that how to use it xD

**Comment by TheKaushikGoswami** [comment]
![image](https://user-images.githubusercontent.com/70503983/118669790-ad850f00-b813-11eb-91e0-f05c17a161af.png)
^^ Well, I already explained about this here...
I hope u firstly read [Readme](https://github.com/TheKaushikGoswami/SPIKE=Discord-Bot/Readme.md) file before explaining me what should i do or not. Thanks! 😄
